<?xml version="1.0" encoding="utf-8"?><Database Name="CloudScriptApplier" Class="ServerDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=majd-pc;Initial Catalog=CloudScriptApplier;Persist Security Info=True;User ID=edward" SettingsObjectName="CloudScriptApplier.Db.Properties.Settings" SettingsPropertyName="CloudScriptApplierConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Databases" Member="Databases">
    <Type Name="Database">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatabaseName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Database_Script" Member="Scripts" ThisKey="Id" OtherKey="DatabaseId" Type="Script" />
      <Association Name="DatabasesType_Database" Member="DatabasesType" ThisKey="DatabaseTypeId" OtherKey="Id" Type="DatabasesType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatabasesType" Member="DatabasesTypes">
    <Type Name="DatabasesType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DatabasesType_Database" Member="Databases" ThisKey="Id" OtherKey="DatabaseTypeId" Type="Database" />
    </Type>
  </Table>
  <Table Name="dbo.LogHistoryType" Member="LogHistoryTypes">
    <Type Name="LogHistoryType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ArName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LogHistoryType_LogHistory" Member="LogHistories" ThisKey="Id" OtherKey="LogHistoryTypeId" Type="LogHistory" />
    </Type>
  </Table>
  <Table Name="dbo.LogHistory" Member="LogHistories">
    <Type Name="LogHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogMessage" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LogHistoryTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Script" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ServerName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DbName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="LogHistoryType_LogHistory" Member="LogHistoryType" ThisKey="LogHistoryTypeId" OtherKey="Id" Type="LogHistoryType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Scripts" Member="Scripts">
    <Type Name="Script">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ScriptText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Database_Script" Member="Database" ThisKey="DatabaseId" OtherKey="Id" Type="Database" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GetRegisteredDatabases" Member="GetRegisteredDatabases">
    <Type Name="GetRegisteredDatabase">
      <Column Name="DatabaseName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>