<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="ClientDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=majd-albaho;Initial Catalog=master;Integrated Security=True" SettingsObjectName="CloudScriptApplier.Db.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
</Database>